name: 'SockBoom Checkin Action'

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    - name: Get log
      uses: actions/checkout@master
    - name: Chick in
      run: |
        echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./run.log
        response=$(curl -X GET 'https://api.sockboom.click/client/checkin?token=${{  secrets.SOCKBOOM_TOKEN }}')
        echo $response
        # checkin_success $(echo $response | jq -r '.success')
        # if [ "$checkin_success" == "1" ]; then
        traffic=$(echo $response | jq -r '.traffic')
        echo -n `date +%Y-%m-%d\ %H:%M:%S`\ -\ >> ./run.log
        echo "$traffic bit" >> ./run.log
        tail run.log #避免日志上传失败丢失日志
        # fi
        # echo "CHECKIN_SUCCCESS=$checkin_success" >> "$GITHUB_ENV"
      env:
          SOCKBOOM_TOKEN: ${{ secrets.SOCKBOOM_TOKEN }}
    - name: Commit #上传日志到仓库，可以自行修改 name 和 email
      env:
       NAME: sockboom-action
       EMAIL: sockboom-action@love98ooo.github.io
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add .
        git commit -m "update log" -a
    - name: Push log
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
